# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='city',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='country',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(blank=True, max_length=96),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='street',
            field=models.CharField(max_length=96),
        ),
    ]
