# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171004_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='When',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thusday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('time', models.TimeField()),
                ('minuteDuration', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='street',
            new_name='adress',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, max_length=196),
        ),
    ]
