# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meeting_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='when',
        ),
        migrations.AddField(
            model_name='when',
            name='meeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='adress',
            field=models.CharField(default='Adress', max_length=96),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='city',
            field=models.CharField(default='City', max_length=96),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='country',
            field=models.CharField(default='Country', max_length=96),
        ),
    ]
