# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171015_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='adress',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='city',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='country',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='when',
            name='meeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Meeting'),
        ),
    ]
