# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_meeting_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='city',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='country',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
