# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171015_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='when',
            name='minuteDuration',
        ),
        migrations.AddField(
            model_name='when',
            name='duration',
            field=models.CharField(default=0, help_text='In minutes', max_length=3),
        ),
        migrations.AlterField(
            model_name='when',
            name='time',
            field=models.TimeField(default='19:00:00'),
        ),
    ]
