# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171015_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(default='', max_length=196),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(default='', max_length=96, unique=True),
        ),
        migrations.AlterField(
            model_name='when',
            name='duration',
            field=models.CharField(default=60, help_text='In minutes', max_length=3),
        ),
    ]
