# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171126_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='area',
            field=models.CharField(choices=[(b'Arizona', b'Arizona'), (b'Colorado', b'Colorado'), (b'Kansas', b'Kansas'), (b'New Mexico', b'New Mexico'), (b'Oklahoma', b'Oklahoma'), (b'North Texas', b'North Texas'), (b'Texas', b'Texas'), (b'South Central Texas', b'South Central Texas'), (b'Southern Colorado', b'Southern Colorado'), (b'Valley Area of Texas', b'Valley Area of Texas'), (b'llinois', b'llinois'), (b'Indiana', b'Indiana'), (b'Kentucky', b'Kentucky'), (b'Manitoba', b'Manitoba'), (b'Michigan', b'Michigan'), (b'Minnesota', b'Minnesota'), (b'Missouri', b'Missouri'), (b'Nebraska', b'Nebraska'), (b'Ohio', b'Ohio'), (b'Wisconsin', b'Wisconsin'), (b'Canadian Maritimes', b'Canadian Maritimes'), (b'Connecticut', b'Connecticut'), (b'Massachusetts', b'Massachusetts'), (b'New York', b'New York'), (b'Northern New England', b'Northern New England'), (b'Eastern Pennsylvania/New Jersey/Delaware', b'Eastern Pennsylvania/New Jersey/Delaware'), (b'Quebec', b'Quebec'), (b'Rhode Island', b'Rhode Island'), (b'Southern Ontario', b'Southern Ontario'), (b'Washington, D.C.', b'Washington, D.C.'), (b'Alabama', b'Alabama'), (b'Arkansas', b'Arkansas'), (b'Florida', b'Florida'), (b'Georgia', b'Georgia'), (b'North Carolina', b'North Carolina'), (b'Louisiana', b'Louisiana'), (b'Tennessee', b'Tennessee'), (b'South Carolina', b'South Carolina'), (b'Virginia', b'Virginia'), (b'Peru', b'Peru'), (b'Antilope Valley', b'Antilope Valley'), (b'Hawaii', b'Hawaii'), (b'Nevada', b'Nevada'), (b'Online', b'Online'), (b'Central California', b'Central California'), (b'Inland Empire', b'Inland Empire'), (b'Los Angeles', b'Los Angeles'), (b'Orange County', b'Orange County'), (b'San Diego', b'San Diego'), (b'San Fernando Valley', b'San Fernando Valley'), (b'San Gabriel/Pomona Valley', b'San Gabriel/Pomona Valley'), (b'Southern Nevada', b'Southern Nevada'), (b'West Inland', b'West Inland'), (b'Alaska', b'Alaska'), (b'British Columbia', b'British Columbia'), (b'Idaho', b'Idaho'), (b'Northern Alberta', b'Northern Alberta'), (b'Northern California', b'Northern California'), (b'Northern Nevada', b'Northern Nevada'), (b'Oregon/Southwest Washington', b'Oregon/Southwest Washington'), (b'Southern Alberta', b'Southern Alberta'), (b'Utah', b'Utah'), (b'Washington', b'Washington'), (b'UK', b'UK'), (b'London', b'London'), (b'Central', b'Central'), (b'Ireland', b'Ireland'), (b'Scotland', b'Scotland'), (b'Holland', b'Holland'), (b'Germany', b'Germany'), (b'Switserland', b'Switserland'), (b'Spain', b'Spain'), (b'Russia', b'Russia'), (b'Sweden', b'Sweden'), (b'Denmark', b'Denmark'), (b'Hong Kong', b'Hong Kong'), (b'South Africa', b'South Africa')], default=b'N/A', max_length=40),
        ),
        migrations.AddField(
            model_name='meeting',
            name='region',
            field=models.CharField(choices=[(b'Europe', b'Europe'), (b'Pacific North', b'Pacific North'), (b'Pacific South', b'Pacific South'), (b'Atlantic North', b'Atlantic North'), (b'Atlantic South', b'Atlantic South'), (b'Mid West', b'Mid West'), (b'South West', b'South West')], default=b'N/A', max_length=40),
        ),
    ]
